### ISSUE TITLE
Triplets on KICKBABA

### ISSUE THREAD

**Issue by strngrthnall** [hampa/comfortzone#2]
I dont know if you still in it but i would like to know if ther is any way to implement triplets bass line on KickBaba
I m gonna give a look on the code, but it would be dope

**Comment by hampa** [comment]
It currently doesn't support it. Definitely possible with some code updates. I'll give it a try. I have a few other things I want to update.

**Comment by strngrthnall** [comment]
I'm just learnig programing , but i'll give a try too.
I just have too give a look on C# language, cus im used to python
